// ─── Government programs for nonprofits & NGOs ───────────────────────────────
// Federal and state programs where 501(c)(3) organizations are primary or
// co-equal applicants. All entries set eligibleEntityTypes + funderType
// explicitly (enrichment never overrides them).

export const nonprofitPrograms = [
  {
    title: "FEMA Nonprofit Security Grant Program (NSGP)",
    slug: "fema-nonprofit-security-grant-program",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "Federal Emergency Management Agency",
    agencyAcronym: "FEMA",
    shortSummary:
      "Funds physical security enhancements for nonprofit organizations at high risk of terrorist or extremist attack — " +
      "security cameras, access controls, blast-resistant doors, lighting, and contracted security personnel. " +
      "Awards are typically up to $150,000 per site, applied for through your state administrative agency.",
    keyRequirements: [
      "Applicant must be a 501(c)(3) nonprofit organization",
      "Must complete a vulnerability/risk assessment of the facility",
      "Application is submitted through the State Administrative Agency (SAA), not directly to FEMA",
      "Investment justification describing threat, vulnerability, and proposed projects required",
      "Funds cover target-hardening equipment and limited security personnel costs",
    ],
    industryCategories: ["Government & Nonprofit", "Infrastructure"],
    incentiveType: "GRANT",
    fundingAmount: 150000,
    deadline: null,
    sourceUrl: "https://www.fema.gov/grants/preparedness/nonprofit-security",
    programCode: "DHS-NSGP",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "GOVERNMENT",
  },
  {
    title: "NEA Grants for Arts Projects",
    slug: "nea-grants-for-arts-projects",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "National Endowment for the Arts",
    agencyAcronym: "NEA",
    shortSummary:
      "The NEA's principal grant program supports public arts projects across all disciplines — dance, music, theater, " +
      "visual arts, media arts, literature, and more. Awards range from $10,000 to $100,000 and require a 1:1 nonfederal cost share. " +
      "Two application deadlines per year.",
    keyRequirements: [
      "Applicant must be a 501(c)(3) nonprofit, unit of state/local government, or federally recognized tribe",
      "Organization must have a 3-year history of arts programming before the application deadline",
      "1:1 cost share/match from nonfederal sources required",
      "Projects must focus on public engagement with the arts or strengthening the arts sector",
      "Apply via Grants.gov during one of the two annual cycles",
    ],
    industryCategories: ["Arts & Culture", "Government & Nonprofit", "Education"],
    incentiveType: "GRANT",
    fundingAmount: 100000,
    deadline: null,
    sourceUrl: "https://www.arts.gov/grants/grants-for-arts-projects",
    programCode: "NEA-GAP",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT", "TRIBAL"],
    funderType: "GOVERNMENT",
  },
  {
    title: "NEH Public Humanities Projects",
    slug: "neh-public-humanities-projects",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "National Endowment for the Humanities",
    agencyAcronym: "NEH",
    shortSummary:
      "Supports museums, historic sites, libraries, and cultural nonprofits producing exhibitions, historic site " +
      "interpretations, and humanities discussion programs for public audiences. Planning grants up to $75,000 and " +
      "implementation grants up to $400,000.",
    keyRequirements: [
      "Applicant must be a U.S. nonprofit with 501(c)(3) status, state/local government, or federally recognized tribe",
      "Projects must be grounded in humanities scholarship with named scholarly advisers",
      "Planning and implementation award tracks have separate budget caps",
      "Applications submitted through Grants.gov by the annual deadline",
    ],
    industryCategories: ["Arts & Culture", "Education", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 400000,
    deadline: null,
    sourceUrl: "https://www.neh.gov/grants/public/public-humanities-projects",
    programCode: "NEH-PHP",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT", "TRIBAL"],
    funderType: "GOVERNMENT",
  },
  {
    title: "AmeriCorps State and National Grants",
    slug: "americorps-state-national-grants",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "AmeriCorps",
    agencyAcronym: "AmeriCorps",
    shortSummary:
      "Provides operating grants to nonprofits, faith-based groups, tribes, and public agencies that engage AmeriCorps " +
      "members in service programs addressing education, poverty, disaster response, environmental stewardship, and public health. " +
      "Grants subsidize member living allowances and program operating costs.",
    keyRequirements: [
      "Applicant must be a nonprofit, tribe, institution of higher education, or state/local public agency",
      "Program design must deploy AmeriCorps members against a documented community need",
      "Match requirement starts at 24% and increases over the life of the grant",
      "Single-state applicants apply through their Governor-appointed State Service Commission",
      "Performance measures and evidence tier documentation required",
    ],
    industryCategories: ["Human Services", "Education", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 400000,
    deadline: null,
    sourceUrl: "https://americorps.gov/funding-opportunity/fy-2025-americorps-state-national-grants",
    programCode: "ACSN",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT", "TRIBAL"],
    funderType: "GOVERNMENT",
  },
  {
    title: "USDA Community Facilities Direct Loan & Grant Program",
    slug: "usda-community-facilities-loan-grant",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "USDA Rural Development",
    agencyAcronym: "USDA RD",
    shortSummary:
      "Finances essential community facilities in rural areas with populations under 20,000 — health clinics, food banks, " +
      "childcare centers, fire stations, community centers, and schools. Nonprofits, municipalities, and tribes can access " +
      "low-interest direct loans, grants covering up to 75% of project costs, or a combination.",
    keyRequirements: [
      "Applicant must be a nonprofit, municipality, county, special-purpose district, or federally recognized tribe",
      "Facility must serve a rural area with population of 20,000 or less",
      "Grant share is tiered by community population and median household income (max 75%)",
      "Applicant must demonstrate legal authority to construct, operate, and maintain the facility",
      "Applications accepted year-round through USDA Rural Development state offices",
    ],
    industryCategories: ["Community Development", "Healthcare", "Infrastructure", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 5000000,
    deadline: null,
    sourceUrl: "https://www.rd.usda.gov/programs-services/community-facilities/community-facilities-direct-loan-grant-program",
    programCode: "USDA-CF",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT", "TRIBAL"],
    funderType: "GOVERNMENT",
  },
  {
    title: "HUD Continuum of Care (CoC) Program",
    slug: "hud-continuum-of-care-program",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "U.S. Department of Housing and Urban Development",
    agencyAcronym: "HUD",
    shortSummary:
      "HUD's largest homelessness assistance program funds nonprofits and government entities operating permanent supportive " +
      "housing, rapid re-housing, transitional housing, and homelessness data systems. Roughly $3 billion is awarded annually " +
      "through an annual national competition organized by local CoC planning bodies.",
    keyRequirements: [
      "Applicant must be a nonprofit organization, state, local government, or instrumentality thereof",
      "Projects must be ranked and submitted through the local Continuum of Care collaborative applicant",
      "Participation in the local Homeless Management Information System (HMIS) required",
      "Housing First implementation is scored in the national competition",
      "25% match required (cash or in-kind) for most project types",
    ],
    industryCategories: ["Housing & Homelessness", "Human Services", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 3000000,
    deadline: null,
    sourceUrl: "https://www.hud.gov/hud-partners/community-coc",
    programCode: "HUD-COC",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT"],
    funderType: "GOVERNMENT",
  },
  {
    title: "FTA Section 5310 — Enhanced Mobility of Seniors & Individuals with Disabilities",
    slug: "fta-section-5310-enhanced-mobility",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "Federal Transit Administration",
    agencyAcronym: "FTA",
    shortSummary:
      "Formula funding that flows through states and large urbanized areas to nonprofits and public bodies providing " +
      "transportation for seniors and people with disabilities — accessible vans and buses, mobility management programs, " +
      "and volunteer driver networks. Federal share is 80% for capital projects.",
    keyRequirements: [
      "Private nonprofit organizations are the priority applicants for traditional capital projects",
      "Public bodies eligible where nonprofit service is unavailable or they coordinate such services",
      "Projects must be included in the area's Coordinated Public Transit-Human Services Transportation Plan",
      "80% federal share for capital, 50% for operating assistance",
      "Apply through your state DOT or designated regional recipient",
    ],
    industryCategories: ["Public Transit", "Human Services", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 500000,
    deadline: null,
    sourceUrl: "https://www.transit.dot.gov/funding/grants/enhanced-mobility-seniors-individuals-disabilities-section-5310",
    programCode: "FTA-5310",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT"],
    funderType: "GOVERNMENT",
  },
  {
    title: "HRSA Rural Health Network Development Planning Program",
    slug: "hrsa-rural-health-network-planning",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "Health Resources and Services Administration",
    agencyAcronym: "HRSA",
    shortSummary:
      "One-year planning grants of up to $100,000 to help rural health networks formalize — integrating care coordination, " +
      "telehealth, workforce sharing, or behavioral health services across at least three separately owned rural provider " +
      "organizations, with nonprofits frequently serving as the network lead.",
    keyRequirements: [
      "Applicant organization must be rural or serve a HRSA-designated rural area",
      "Network must include at least three separately owned health-related organizations",
      "Nonprofit, public, and tribal entities are eligible applicant types",
      "Funds support planning activities, not direct clinical services",
      "Apply via Grants.gov during the annual competition cycle",
    ],
    industryCategories: ["Healthcare", "Government & Nonprofit", "Community Development"],
    incentiveType: "GRANT",
    fundingAmount: 100000,
    deadline: null,
    sourceUrl: "https://www.hrsa.gov/rural-health/grants",
    programCode: "HRSA-RHND",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT", "TRIBAL"],
    funderType: "GOVERNMENT",
  },
  {
    title: "CDFI Fund Financial Assistance & Technical Assistance Awards",
    slug: "cdfi-fund-financial-technical-assistance",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "U.S. Department of the Treasury — CDFI Fund",
    agencyAcronym: "CDFI",
    shortSummary:
      "Provides capital grants up to $2 million to certified Community Development Financial Institutions — many of them " +
      "nonprofit loan funds — that finance affordable housing, small businesses, and community facilities in underserved " +
      "markets. Smaller Technical Assistance grants (up to $125,000) help emerging CDFIs build capacity.",
    keyRequirements: [
      "Financial Assistance applicants must be certified CDFIs at time of application",
      "Technical Assistance track open to emerging entities working toward certification",
      "FA awards must be matched with non-federal funds of comparable form and value",
      "Awardees commit to deploying capital in eligible target markets",
      "Annual application round via the CDFI Fund AMIS portal",
    ],
    industryCategories: ["Financial Services", "Community Development", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 2000000,
    deadline: null,
    sourceUrl: "https://www.cdfifund.gov/programs-training/programs/cdfi-program",
    programCode: "CDFI-FA",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "BUSINESS"],
    funderType: "GOVERNMENT",
  },
  {
    title: "EPA Environmental Education (EE) Grants",
    slug: "epa-environmental-education-grants",
    jurisdictionLevel: "FEDERAL",
    jurisdictionName: "United States",
    managingAgency: "U.S. Environmental Protection Agency",
    agencyAcronym: "EPA",
    shortSummary:
      "Supports locally focused environmental education projects that increase public awareness and stewardship — teacher " +
      "training, community science, watershed education, and youth programs. Typical awards range from $50,000 to $100,000; " +
      "nonprofits, schools, and state/local/tribal agencies are eligible.",
    keyRequirements: [
      "Applicant must be a 501(c)(3) nonprofit, education institution, or state/local/tribal agency",
      "Project must deliver environmental education, not just information dissemination",
      "Non-federal match of at least 25% of total project cost required",
      "Competition cycles announced periodically — confirm current NOFO status on the EPA EE page",
    ],
    industryCategories: ["Environment & Conservation", "Education", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 100000,
    deadline: null,
    sourceUrl: "https://www.epa.gov/education/environmental-education-ee-grants",
    programCode: "EPA-EE",
    status: "ACTIVE",
    isVerified: false,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT", "TRIBAL"],
    funderType: "GOVERNMENT",
  },
  {
    title: "NYSCA Support for Organizations Grants",
    slug: "nysca-support-for-organizations",
    jurisdictionLevel: "STATE",
    jurisdictionName: "New York",
    managingAgency: "New York State Council on the Arts",
    agencyAcronym: "NYSCA",
    shortSummary:
      "New York's flagship arts funding stream provides general operating and programmatic support to nonprofit arts and " +
      "cultural organizations across the state — from community theaters to major museums. Annual awards commonly range " +
      "from $10,000 to $49,500 depending on organizational budget size.",
    keyRequirements: [
      "Applicant must be a New York State nonprofit with 501(c)(3) status or use a fiscal sponsor",
      "Organization must have a minimum one-year history of arts programming in NYS",
      "Apply through the NYSCA online grants portal during the annual cycle",
      "Cannot hold overlapping NYSCA awards for the same activity",
    ],
    industryCategories: ["Arts & Culture", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 49500,
    deadline: null,
    sourceUrl: "https://arts.ny.gov/grants",
    programCode: "NYSCA-SFO",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "GOVERNMENT",
  },
  {
    title: "California Arts Council — General Operating Support",
    slug: "california-arts-council-general-operating",
    jurisdictionLevel: "STATE",
    jurisdictionName: "California",
    managingAgency: "California Arts Council",
    agencyAcronym: "CAC",
    shortSummary:
      "Provides flexible general operating grants to California nonprofit arts organizations, prioritizing organizations " +
      "rooted in historically underserved communities. Funds can support staff, rent, programming, and other core costs " +
      "rather than being tied to a single project.",
    keyRequirements: [
      "Applicant must be a California-based nonprofit arts organization or fiscally sponsored arts group",
      "Minimum two-year history of arts programming in California",
      "Grant amounts scale with organizational budget; consult current program guidelines",
      "Apply during the annual grant cycle via the CAC portal",
    ],
    industryCategories: ["Arts & Culture", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 30000,
    deadline: null,
    sourceUrl: "https://arts.ca.gov/grants/",
    programCode: "CAC-GOS",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "GOVERNMENT",
  },
  {
    title: "Texas Commission on the Arts — Arts Create Grants",
    slug: "texas-commission-arts-create",
    jurisdictionLevel: "STATE",
    jurisdictionName: "Texas",
    managingAgency: "Texas Commission on the Arts",
    agencyAcronym: "TCA",
    shortSummary:
      "Provides operational support to Texas nonprofit arts organizations whose primary mission is arts programming — " +
      "theaters, symphonies, museums, dance companies, and arts education groups. Awards are calculated against " +
      "organizational budget with a required 1:1 match.",
    keyRequirements: [
      "Applicant must be a Texas 501(c)(3) whose primary purpose is arts programming",
      "Must have completed at least two consecutive years of arts programming",
      "1:1 match required from non-TCA sources",
      "Annual application via the TCA online grant system",
    ],
    industryCategories: ["Arts & Culture", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 75000,
    deadline: null,
    sourceUrl: "https://www.arts.texas.gov/grants/",
    programCode: "TCA-AC",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "GOVERNMENT",
  },
  {
    title: "Massachusetts Cultural Council — Cultural Sector Recovery & Operating Grants",
    slug: "mass-cultural-council-operating-grants",
    jurisdictionLevel: "STATE",
    jurisdictionName: "Massachusetts",
    managingAgency: "Massachusetts Cultural Council",
    agencyAcronym: "Mass Cultural",
    shortSummary:
      "State cultural agency grants providing unrestricted operating support to Massachusetts cultural nonprofits — " +
      "arts, humanities, and interpretive sciences organizations. The CIP Projects and Portfolio tracks fund both " +
      "one-time projects and multi-year operating needs.",
    keyRequirements: [
      "Applicant must be a Massachusetts-based cultural nonprofit or fiscally sponsored group",
      "Public programming in the arts, humanities, or interpretive sciences required",
      "Award size scales with budget; portfolio organizations receive multi-year support",
      "Apply during the annual cycle through the MCC grants portal",
    ],
    industryCategories: ["Arts & Culture", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 50000,
    deadline: null,
    sourceUrl: "https://massculturalcouncil.org/organizations/",
    programCode: "MCC-OP",
    status: "ACTIVE",
    isVerified: false,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "GOVERNMENT",
  },
];
