// California air quality district + state agency programs
export const caPrograms = [
  {
    title: "SMAQMD Carl Moyer Program — On-Road & Off-Road Equipment",
    slug: "smaqmd-carl-moyer",
    jurisdictionLevel: "AGENCY", jurisdictionName: "Sacramento, CA",
    managingAgency: "Sacramento Metropolitan Air Quality Management District", agencyAcronym: "SMAQMD",
    shortSummary: "Grants to replace older diesel engines in on-road trucks, off-road construction and agricultural equipment, and marine vessels operated in the Sacramento region. Covers Tier 4 Final diesel, CNG, and zero-emission replacements with funding up to 80% of incremental cost.",
    keyRequirements: JSON.stringify(["Equipment must operate primarily in the Sacramento Metropolitan Air Basin","Old engine must be Tier 0, Tier 1, or Tier 2 diesel","Business must have owned equipment for at least 2 years prior to application","Equipment must remain in the Sacramento district for 5 years post-grant","Agricultural, construction, fleet businesses and government agencies qualify"]),
    industryCategories: JSON.stringify(["Agriculture","Construction","Fleet","Logistics"]),
    incentiveType: "GRANT", fundingAmount: 250000, deadline: null,
    sourceUrl: "https://www.airquality.org/businesses/grants-incentives/carl-moyer-program", programCode: "SMAQMD-CM", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "SJVAPCD FARMER — Funding Agricultural Replacement Measures for Emission Reductions",
    slug: "sjvapcd-farmer",
    jurisdictionLevel: "AGENCY", jurisdictionName: "San Joaquin Valley, CA",
    managingAgency: "San Joaquin Valley Air Pollution Control District", agencyAcronym: "SJVAPCD",
    shortSummary: "Grants for San Joaquin Valley farms to replace older diesel tractors, harvesters, and implements with cleaner Tier 4 or zero-emission alternatives. Funded through California's Greenhouse Gas Reduction Fund; ZEV replacements can receive up to 100% of incremental cost.",
    keyRequirements: JSON.stringify(["Agricultural equipment operated within the San Joaquin Valley Air Basin","Old equipment must be diesel-powered Tier 0–2 agricultural implement","Actively used in farming operations — commercial agricultural businesses qualify","ZEV and near-ZEV equipment receives highest reimbursement tier (up to 100% incremental cost)","Equipment must remain in the Valley for a minimum of 5 years"]),
    industryCategories: JSON.stringify(["Agriculture","Construction"]),
    incentiveType: "GRANT", fundingAmount: 300000, deadline: null,
    sourceUrl: "https://www.valleyair.org/grant_programs/FARMER/farmer_main.htm", programCode: "SJVAPCD-FARMER", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "San Diego APCD Mobile Source Incentive Program (MSIP)",
    slug: "sdapcd-msip",
    jurisdictionLevel: "AGENCY", jurisdictionName: "San Diego, CA",
    managingAgency: "San Diego County Air Pollution Control District", agencyAcronym: "SDAPCD",
    shortSummary: "Carl Moyer and TFCA grants for San Diego County businesses and public agencies operating older diesel trucks, buses, and off-road equipment. Covers replacement and repower with Tier 4 Final or zero-emission technologies.",
    keyRequirements: JSON.stringify(["Equipment must be primarily operated in San Diego County","Old vehicle/equipment must be diesel-powered and meet minimum age criteria","Replacement must be Tier 4 Final or zero-emission certified","Applicant must be a San Diego County business, nonprofit, or government agency","Equipment must remain in San Diego County for at least 5 years post-purchase"]),
    industryCategories: JSON.stringify(["Fleet","Construction","Logistics","Agriculture"]),
    incentiveType: "GRANT", fundingAmount: 200000, deadline: null,
    sourceUrl: "https://www.sdapcd.org/content/sdc/apcd/en/mobile-sources/incentive-programs.html", programCode: "SDAPCD-MSIP", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "BAAQMD TFCA Regional Fund — Clean Vehicles & Infrastructure",
    slug: "baaqmd-tfca-regional",
    jurisdictionLevel: "AGENCY", jurisdictionName: "Bay Area, CA",
    managingAgency: "Bay Area Air Quality Management District", agencyAcronym: "BAAQMD",
    shortSummary: "Bay Area AQMD Transportation Fund for Clean Air (TFCA) grants for ZEV purchases, EV charging infrastructure, trip reduction, and bicycle facilities in the nine-county Bay Area region. Funded by a $4 surcharge on motor vehicle registrations.",
    keyRequirements: JSON.stringify(["Project must be in the Bay Area Air Basin (9-county region)","Eligible: ZEV purchases, EV charging infrastructure, trip-reduction programs","Public agency, nonprofit, or Bay Area business must apply","Must meet minimum emission reduction per dollar cost-effectiveness threshold","Annual solicitation; minimum project cost typically $50,000"]),
    industryCategories: JSON.stringify(["Fleet","EV Charging","Public Transit","Clean Technology"]),
    incentiveType: "GRANT", fundingAmount: 500000, deadline: null,
    sourceUrl: "https://www.baaqmd.gov/funding-and-incentives/businesses-and-fleets/tfca-regional-fund", programCode: "BAAQMD-TFCA", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Ventura County APCD Agricultural Equipment Replacement Program",
    slug: "vcapcd-ag-equipment-replacement",
    jurisdictionLevel: "AGENCY", jurisdictionName: "Ventura County, CA",
    managingAgency: "Ventura County Air Pollution Control District", agencyAcronym: "VCAPCD",
    shortSummary: "Carl Moyer Program grants for Ventura County farmers and agricultural businesses to replace older Tier 0–1 diesel farm equipment with Tier 4 Final or zero-emission alternatives. Particularly relevant for strawberry, citrus, and avocado operations.",
    keyRequirements: JSON.stringify(["Equipment must be primarily operated in Ventura County","Existing engine must be Tier 0 or Tier 1 diesel agricultural equipment","Business must have owned the equipment for at least 2 years","Replacement must be Tier 4 Final diesel, electric, or hydrogen-powered","Grant covers incremental cost above Tier 2 baseline"]),
    industryCategories: JSON.stringify(["Agriculture","Construction"]),
    incentiveType: "GRANT", fundingAmount: 150000, deadline: null,
    sourceUrl: "https://www.vcapcd.org/programs/MobileSource.htm", programCode: "VCAPCD-AGR", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "CEC Industrial Decarbonization Program",
    slug: "cec-industrial-decarbonization",
    jurisdictionLevel: "STATE", jurisdictionName: "California",
    managingAgency: "California Energy Commission", agencyAcronym: "CEC",
    shortSummary: "Grants for California industrial facilities to electrify fossil fuel processes using electricity, hydrogen, or other clean energy sources. Emphasis on cement, glass, food processing, and other energy-intensive sectors in disadvantaged communities.",
    keyRequirements: JSON.stringify(["Industrial facility or manufacturer located in California","Project must directly reduce or eliminate fossil fuel combustion in industrial process","Priority for facilities in Disadvantaged Communities (CalEnviroScreen top quartile)","Eligible: electric process heat, hydrogen furnaces, heat pumps, electrolysis","Grant range: $500K–$5M; cost-share of 20–50% required"]),
    industryCategories: JSON.stringify(["Manufacturing","Clean Technology","Energy Management","Building Electrification"]),
    incentiveType: "GRANT", fundingAmount: 5000000, deadline: null,
    sourceUrl: "https://www.energy.ca.gov/programs-and-topics/programs/industrial-decarbonization", programCode: "CEC-INDEC", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "CEC Clean Transportation Program — Hydrogen Fueling Infrastructure",
    slug: "cec-clean-transport-hydrogen",
    jurisdictionLevel: "STATE", jurisdictionName: "California",
    managingAgency: "California Energy Commission", agencyAcronym: "CEC",
    shortSummary: "CEC grants up to $4M for developing hydrogen fueling stations supporting Class 8 trucks and transit buses in California. Part of AB 8 and SB 1505 hydrogen station network build-out with priority for corridor locations.",
    keyRequirements: JSON.stringify(["New hydrogen fueling station or significant expansion in California","Station must serve light-, medium-, or heavy-duty FCEVs","Priority for stations in hydrogen network corridors identified by CEC","Retail H2 price must meet CEC affordability thresholds","25% cost-share required; viable business plan required"]),
    industryCategories: JSON.stringify(["Fleet","Clean Technology","EV Charging","Logistics"]),
    incentiveType: "GRANT", fundingAmount: 4000000, deadline: null,
    sourceUrl: "https://www.energy.ca.gov/programs-and-topics/programs/clean-transportation-program", programCode: "CEC-CTP-H2", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "California Competes Tax Credit (CCTC)",
    slug: "california-competes-tax-credit",
    jurisdictionLevel: "STATE", jurisdictionName: "California",
    managingAgency: "California Governor's Office of Business and Economic Development", agencyAcronym: "GO-Biz",
    shortSummary: "Negotiated income tax credits for businesses that grow in California and create new jobs. Over $180M available annually through three competitive application periods per year. Credits range from $1,000 to $100,000+ per net new job created.",
    keyRequirements: JSON.stringify(["Business must be located in or relocating to California","Must commit to creating new full-time jobs above minimum wage threshold","Apply during one of GO-Biz's 3 annual application windows","5-year compliance period with annual job and wage reporting","Priority for businesses in high-unemployment areas and targeted industries"]),
    industryCategories: JSON.stringify(["Manufacturing","Technology","Clean Technology","Healthcare","Logistics"]),
    incentiveType: "TAX_CREDIT", fundingAmount: 10000000, deadline: null,
    sourceUrl: "https://business.ca.gov/california-competes-tax-credit/", programCode: "CA-CCTC", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "CalSTA Sustainable Transportation Equity Project (STEP)",
    slug: "calsta-step",
    jurisdictionLevel: "STATE", jurisdictionName: "California",
    managingAgency: "California State Transportation Agency", agencyAcronym: "CalSTA",
    shortSummary: "Grants for zero-emission transportation projects serving disadvantaged, low-income, and rural California communities. Funds EV charging infrastructure, ZEV car-sharing, last-mile transit connections, and small business fleet electrification.",
    keyRequirements: JSON.stringify(["Project must primarily benefit disadvantaged, low-income, or rural communities (SB 535 definition)","Eligible: EV charging hubs, ZEV car-sharing, community shuttles, last-mile delivery ZEV fleets","Public agencies, nonprofits, tribal governments, or community organizations apply","Grant range: $100K–$3M per project, prioritized for equity impact"]),
    industryCategories: JSON.stringify(["EV Charging","Fleet","Public Transit","Clean Technology"]),
    incentiveType: "GRANT", fundingAmount: 3000000, deadline: null,
    sourceUrl: "https://calsta.ca.gov/subject-areas/sustainable-transportation-equity-project", programCode: "CALSTA-STEP", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "CDFA Healthy Soils Program",
    slug: "cdfa-healthy-soils",
    jurisdictionLevel: "STATE", jurisdictionName: "California",
    managingAgency: "California Department of Food and Agriculture", agencyAcronym: "CDFA",
    shortSummary: "Grants for California agricultural operations to implement soil health practices that sequester carbon and reduce greenhouse gas emissions. Funds cover-cropping, compost application, reduced tillage, mulching, and agroforestry — funded through California's Greenhouse Gas Reduction Fund.",
    keyRequirements: JSON.stringify(["Agricultural operation located in California","Eligible: cover cropping, compost application, mulching, reduced tillage, agroforestry","Must implement CDFA-approved practice for a minimum 3-year period","Grant range: $10,000–$100,000 per applicant","Priority for operations in Disadvantaged Communities or serving disadvantaged farmers"]),
    industryCategories: JSON.stringify(["Agriculture","Clean Technology"]),
    incentiveType: "GRANT", fundingAmount: 100000, deadline: null,
    sourceUrl: "https://www.cdfa.ca.gov/oefi/healthysoils/", programCode: "CDFA-HSP", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "CDFA State Water Efficiency and Enhancement Program (SWEEP)",
    slug: "cdfa-sweep",
    jurisdictionLevel: "STATE", jurisdictionName: "California",
    managingAgency: "California Department of Food and Agriculture", agencyAcronym: "CDFA",
    shortSummary: "Grants for California farmers to install drip irrigation, soil moisture sensors, pump upgrades, and solar-powered irrigation systems that reduce water use and associated greenhouse gas emissions.",
    keyRequirements: JSON.stringify(["Agricultural operation with active irrigation in California","Eligible: drip/micro-irrigation conversion, soil moisture monitoring, pump efficiency upgrades, solar-powered irrigation","Grant range: $10,000–$200,000 depending on farm size and project scope","Priority for small-to-medium farms and operations in Disadvantaged Communities","Annual competitive solicitation through CDFA"]),
    industryCategories: JSON.stringify(["Agriculture","Water & Utilities","Energy Management"]),
    incentiveType: "GRANT", fundingAmount: 200000, deadline: null,
    sourceUrl: "https://www.cdfa.ca.gov/oefi/sweep/", programCode: "CDFA-SWEEP", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "California TECH Clean Homes — Multifamily Electrification Rebates",
    slug: "ca-tech-clean-homes-multifamily",
    jurisdictionLevel: "STATE", jurisdictionName: "California",
    managingAgency: "California Energy Commission", agencyAcronym: "CEC",
    shortSummary: "Rebates of $3,000–$6,000 per unit for multifamily building owners installing heat pump HVAC and water heaters. TECH Clean California offers enhanced incentives for low-income properties and requires installation by a participating contractor.",
    keyRequirements: JSON.stringify(["Multifamily residential building in California (5+ units preferred)","Property owner or authorized manager must apply","Eligible measures: heat pump water heaters, heat pump HVAC, electric panel upgrades","Enhanced incentives for low-income designated properties (up to double standard rebate)","Equipment must be installed by a participating TECH contractor"]),
    industryCategories: JSON.stringify(["Building Electrification","Real Estate","Energy Management"]),
    incentiveType: "POINT_OF_SALE_REBATE", fundingAmount: 6000, deadline: null,
    sourceUrl: "https://techcleanca.com/", programCode: "CA-TECH", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "California Equitable Building Decarbonization (EBD) Program",
    slug: "ca-equitable-building-decarbonization",
    jurisdictionLevel: "STATE", jurisdictionName: "California",
    managingAgency: "California Energy Commission", agencyAcronym: "CEC",
    shortSummary: "Grants up to $40,000 per unit for comprehensive electrification of low-income multifamily and single-family homes — replacing gas heating, cooking, and water heating bundled with insulation and weatherization measures.",
    keyRequirements: JSON.stringify(["Building must be a low-income or affordable housing property","Must complete a minimum all-electric scope (heat pump HVAC, heat pump water heater, electric cooktop, insulation)","Property owner or qualified nonprofit housing organization applies","Priority for buildings in highest-need Disadvantaged Communities","CEC-approved contractors required"]),
    industryCategories: JSON.stringify(["Building Electrification","Real Estate","Government & Nonprofit"]),
    incentiveType: "GRANT", fundingAmount: 40000, deadline: null,
    sourceUrl: "https://www.energy.ca.gov/programs-and-topics/programs/equitable-building-decarbonization", programCode: "CA-EBD", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "CAEATFA Sales & Use Tax Exemption — Clean Manufacturing Equipment",
    slug: "ca-caeatfa-sales-tax-exemption",
    jurisdictionLevel: "STATE", jurisdictionName: "California",
    managingAgency: "California Alternative Energy and Advanced Transportation Financing Authority", agencyAcronym: "CAEATFA",
    shortSummary: "Full state and local sales and use tax exemption (7.25–10%) on equipment purchases for California manufacturers of solar, wind, batteries, EVs, fuel cells, and green building materials. Reduces equipment procurement costs with board pre-approval.",
    keyRequirements: JSON.stringify(["Manufacturer must be in California in a qualifying industry: solar, wind, batteries, EVs, fuel cells, green building","Exemption applies to manufacturing equipment, machinery, and tools used in qualifying production","Application to CAEATFA board required before purchasing equipment","Certificate of Exemption presented to equipment vendor at purchase","No minimum investment required, though minimum $1M recommended for cost-effectiveness"]),
    industryCategories: JSON.stringify(["Manufacturing","Clean Technology","Energy Storage","Automotive"]),
    incentiveType: "TAX_CREDIT", fundingAmount: null, deadline: null,
    sourceUrl: "https://www.treasurer.ca.gov/caeatfa/suTaxExemption/", programCode: "CA-CAEATFA-SUT", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "PG&E EV Fleet Charging for Business",
    slug: "pge-ev-fleet-charging-business",
    jurisdictionLevel: "AGENCY", jurisdictionName: "Northern & Central California",
    managingAgency: "Pacific Gas and Electric Company", agencyAcronym: "PG&E",
    shortSummary: "PG&E provides make-ready charging infrastructure rebates up to $500 per Level 2 port and $10,000 per DCFC for businesses in PG&E territory electrifying fleets of 10+ vehicles. Includes managed charging services and EV fleet tariff rates.",
    keyRequirements: JSON.stringify(["Business must be a PG&E commercial customer in Northern/Central CA","Fleet electrification project of 10+ vehicles planned or underway","Make-ready rebate: up to $500/Level 2 port, $10,000/DCFC","Must enroll in PG&E EV Fleet rate tariff (BEV or EV-B tariff)","Managed charging agreement required for full program benefits"]),
    industryCategories: JSON.stringify(["EV Charging","Fleet","Logistics","Real Estate"]),
    incentiveType: "SUBSIDY", fundingAmount: 500000, deadline: null,
    sourceUrl: "https://www.pge.com/en/business/save-energy-money/ev-fleet.html", programCode: "PGE-EVFLEET", status: "ACTIVE", isVerified: true, scraperSource: "utility_scraper",
  },
  {
    title: "SCE Charge Ready Program — Commercial EV Charging Infrastructure",
    slug: "sce-charge-ready",
    jurisdictionLevel: "AGENCY", jurisdictionName: "Southern California",
    managingAgency: "Southern California Edison", agencyAcronym: "SCE",
    shortSummary: "SCE installs and owns make-ready electrical infrastructure (wiring, panels, transformers) for EV charging at eligible customer sites at no upfront cost. Businesses get charging-ready parking without paying for grid upgrades — minimum 4 EV spaces required.",
    keyRequirements: JSON.stringify(["Business or property owner in SCE service territory (Southern CA, excluding LADWP)","Eligible sites: workplaces, multi-unit dwellings, public parking, fleet depots","SCE owns and maintains make-ready electrical infrastructure at no charge","Customer provides EV charging stations (EVSE) and may receive equipment rebate","Minimum 4 EV charging spaces required to qualify"]),
    industryCategories: JSON.stringify(["EV Charging","Real Estate","Fleet","Logistics"]),
    incentiveType: "SUBSIDY", fundingAmount: 500000, deadline: null,
    sourceUrl: "https://www.sce.com/business/electric-vehicles/charge-ready", programCode: "SCE-CR", status: "ACTIVE", isVerified: true, scraperSource: "utility_scraper",
  },
];
