// ─── Foundation & corporate funding for nonprofits ───────────────────────────
// Private philanthropy: national foundations, place-based foundations, and
// corporate giving programs. jurisdictionLevel FOUNDATION distinguishes these
// from government sources; funderType separates FOUNDATION vs CORPORATE.
// Several major foundations work by letter of inquiry (LOI) or invitation —
// requirements note this explicitly so applicants aren't misled.

export const foundationPrograms = [
  {
    title: "MacArthur Foundation — 100&Change Competition",
    slug: "macarthur-100-and-change",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "John D. and Catherine T. MacArthur Foundation",
    agencyAcronym: "MacArthur",
    shortSummary:
      "A recurring global competition awarding a single $100 million grant to fund one bold solution to a critical " +
      "problem of our time. Open to nonprofits and NGOs worldwide; finalists receive capacity-building support and " +
      "exposure to co-funders through the Bold Solutions Network.",
    keyRequirements: [
      "Open to nonprofit organizations and NGOs; teams may include for-profit partners",
      "Proposal must address a significant problem with a verifiable, durable, and feasible solution",
      "Registration and multi-stage peer review during open competition windows (roughly every 3 years)",
      "Top proposals join the Bold Solutions Network for visibility to other funders",
    ],
    industryCategories: ["Government & Nonprofit", "Human Services", "Research & Development"],
    incentiveType: "GRANT",
    fundingAmount: 100000000,
    deadline: null,
    sourceUrl: "https://www.macfound.org/programs/100change/",
    programCode: "MAC-100C",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "FOUNDATION",
  },
  {
    title: "Ford Foundation — BUILD General Operating Support",
    slug: "ford-foundation-build",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "Ford Foundation",
    agencyAcronym: "Ford",
    shortSummary:
      "Five-year, flexible general operating support grants that strengthen social justice organizations' institutional " +
      "resilience — core budgets, financial reserves, and organizational development rather than individual projects. " +
      "Grantees are identified through Ford's program teams; there is no open application portal.",
    keyRequirements: [
      "Organizations aligned with Ford's social justice program areas",
      "Selection is by invitation through program officers — unsolicited proposals are generally not accepted",
      "BUILD grants combine multi-year general support with institutional strengthening funds",
      "U.S. and international social justice organizations have been funded",
    ],
    industryCategories: ["Government & Nonprofit", "Human Services"],
    incentiveType: "GRANT",
    fundingAmount: 1000000,
    deadline: null,
    sourceUrl: "https://www.fordfoundation.org/work/our-grants/building-institutions-and-networks/",
    programCode: "FORD-BUILD",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "FOUNDATION",
  },
  {
    title: "Kresge Foundation — Environment & American Cities Grants",
    slug: "kresge-foundation-environment-cities",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "The Kresge Foundation",
    agencyAcronym: "Kresge",
    shortSummary:
      "Funds nonprofits helping U.S. cities — particularly low-income communities — build climate resilience, advance " +
      "equitable clean energy, and strengthen community development systems. Kresge periodically posts open funding " +
      "opportunities alongside invited grantmaking across its Environment, Health, and American Cities programs.",
    keyRequirements: [
      "U.S. 501(c)(3) organizations or fiscally sponsored projects",
      "Work must align with a current Kresge program strategy (climate resilience, creative placemaking, health equity)",
      "Check the foundation's 'Current funding opportunities' page for open RFPs; other grants are invited",
      "Both project grants and multi-year general operating support are used",
    ],
    industryCategories: ["Environment & Conservation", "Community Development", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 500000,
    deadline: null,
    sourceUrl: "https://kresge.org/grants-social-investments/current-funding-opportunities/",
    programCode: "KRESGE-ENV",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "FOUNDATION",
  },
  {
    title: "Robert Wood Johnson Foundation — Health Equity Funding Opportunities",
    slug: "rwjf-health-equity-grants",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "Robert Wood Johnson Foundation",
    agencyAcronym: "RWJF",
    shortSummary:
      "The largest U.S. philanthropy devoted to health regularly releases open calls for proposals — research on health " +
      "equity, community-led health initiatives, and policy work addressing the social determinants of health. Nonprofits, " +
      "universities, and public agencies are eligible for most calls.",
    keyRequirements: [
      "Eligibility varies by call — most are open to 501(c)(3)s, public entities, and universities",
      "Active CFPs are listed on RWJF's funding opportunities page with fixed deadlines",
      "Proposals must advance health equity outcomes consistent with the specific call",
      "Budgets and durations vary widely by program ($50K pilots to multi-million-dollar initiatives)",
    ],
    industryCategories: ["Healthcare", "Human Services", "Government & Nonprofit", "Research & Development"],
    incentiveType: "GRANT",
    fundingAmount: 500000,
    deadline: null,
    sourceUrl: "https://www.rwjf.org/en/grants/active-funding-opportunities.html",
    programCode: "RWJF-OPEN",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT"],
    funderType: "FOUNDATION",
  },
  {
    title: "W.K. Kellogg Foundation Grants",
    slug: "wk-kellogg-foundation-grants",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "W.K. Kellogg Foundation",
    agencyAcronym: "WKKF",
    shortSummary:
      "Accepts unsolicited grant applications year-round through an online portal — unusual among large national " +
      "foundations. Funds organizations improving conditions for children and families: early childhood education, " +
      "children's health, family economic security, and racial equity, with priority places including Michigan, " +
      "Mississippi, New Mexico, and New Orleans.",
    keyRequirements: [
      "Applicant is typically a 501(c)(3) public charity or government instrumentality",
      "Work must align with WKKF priorities: thriving children, working families, equitable communities",
      "Online application accepted on a rolling basis; initial response usually within 30 days",
      "Priority geographies receive heightened attention but national work is funded",
    ],
    industryCategories: ["Human Services", "Education", "Healthcare", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 250000,
    deadline: null,
    sourceUrl: "https://www.wkkf.org/grantseekers/",
    programCode: "WKKF",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT"],
    funderType: "FOUNDATION",
  },
  {
    title: "Charles Stewart Mott Foundation Grants",
    slug: "mott-foundation-grants",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "Charles Stewart Mott Foundation",
    agencyAcronym: "Mott",
    shortSummary:
      "Funds nonprofits in four areas: civil society, environment (freshwater conservation and climate), education " +
      "(afterschool learning), and revitalizing its hometown of Flint, Michigan. Grantseekers submit a letter of inquiry " +
      "online; full proposals are by invitation after LOI review.",
    keyRequirements: [
      "U.S. 501(c)(3) organizations (or international equivalents) aligned with a Mott program area",
      "Start with a letter of inquiry via the foundation's website — full proposals by invitation",
      "Environment program emphasizes Great Lakes freshwater protection and the clean energy transition",
      "Education program focuses on afterschool and expanded learning systems",
    ],
    industryCategories: ["Environment & Conservation", "Education", "Community Development", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 200000,
    deadline: null,
    sourceUrl: "https://www.mott.org/grants/grantseekers/",
    programCode: "MOTT",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "FOUNDATION",
  },
  {
    title: "David & Lucile Packard Foundation Grants",
    slug: "packard-foundation-grants",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "David and Lucile Packard Foundation",
    agencyAcronym: "Packard",
    shortSummary:
      "Major philanthropic funder of ocean and land conservation, climate action, reproductive health, and children's " +
      "wellbeing, with dedicated local grantmaking in California's San Mateo, Santa Clara, Santa Cruz, San Benito, and " +
      "Monterey counties. Most grants originate with program staff; local grantmaking has defined application windows.",
    keyRequirements: [
      "501(c)(3) organizations (or equivalent) working within a Packard program strategy",
      "National/global programs are largely staff-initiated — review strategy pages before outreach",
      "California local grantmaking accepts applications from organizations in the five focal counties",
      "Multi-year general operating support is common for aligned grantees",
    ],
    industryCategories: ["Environment & Conservation", "Healthcare", "Human Services", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 300000,
    deadline: null,
    sourceUrl: "https://www.packard.org/grants-and-investments/for-grantseekers/",
    programCode: "PACKARD",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "FOUNDATION",
  },
  {
    title: "Walton Family Foundation — Environment Program Grants",
    slug: "walton-family-foundation-environment",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "Walton Family Foundation",
    agencyAcronym: "WFF",
    shortSummary:
      "Funds nonprofits working on ocean and river conservation — sustainable fisheries, Colorado River and Mississippi " +
      "River basin health, and coastal community resilience — alongside K-12 education reform and quality-of-life " +
      "initiatives in Northwest Arkansas and the Arkansas-Mississippi Delta.",
    keyRequirements: [
      "501(c)(3) organizations aligned with a current WFF initiative strategy",
      "Most grants are initiated through program staff relationships; review strategies before submitting inquiries",
      "Environment program prioritizes measurable conservation outcomes with community benefit",
      "Education grants focus on expanding high-quality K-12 school options",
    ],
    industryCategories: ["Environment & Conservation", "Education", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 300000,
    deadline: null,
    sourceUrl: "https://www.waltonfamilyfoundation.org/grants",
    programCode: "WFF-ENV",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "FOUNDATION",
  },
  {
    title: "The California Endowment — Health Equity Grants",
    slug: "california-endowment-health-equity",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "California",
    managingAgency: "The California Endowment",
    agencyAcronym: "TCE",
    shortSummary:
      "California's largest health foundation funds community-based nonprofits advancing health equity and racial " +
      "justice — community power building, youth organizing, health access for underserved Californians, and healthy " +
      "community infrastructure. Accepts online funding inquiries from California organizations.",
    keyRequirements: [
      "Applicant must serve California communities; 501(c)(3) or fiscally sponsored",
      "Work should align with TCE's health equity and community power-building strategy",
      "Submit an online inquiry through the foundation's grantseeker portal",
      "Both project support and general operating grants are made",
    ],
    industryCategories: ["Healthcare", "Human Services", "Community Development", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 200000,
    deadline: null,
    sourceUrl: "https://www.calendow.org/",
    programCode: "TCE-HE",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "FOUNDATION",
  },
  {
    title: "The New York Community Trust — Competitive Grants",
    slug: "new-york-community-trust-grants",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "New York",
    managingAgency: "The New York Community Trust",
    agencyAcronym: "NYCT",
    shortSummary:
      "One of the nation's largest community foundations makes competitive grants to nonprofits serving New York City, " +
      "Westchester, and Long Island — arts, education, health, human services, environment, and civic affairs. " +
      "Proposals are accepted year-round through an online portal with published program guidelines.",
    keyRequirements: [
      "Applicant must be a 501(c)(3) serving NYC, Westchester, or Long Island",
      "Project must fit a current NYCT grantmaking guideline area",
      "Submit full proposals through the online grants portal; decisions in quarterly board cycles",
      "Typical competitive grants range from $50,000 to $150,000 over 1-2 years",
    ],
    industryCategories: ["Human Services", "Arts & Culture", "Education", "Healthcare", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 150000,
    deadline: null,
    sourceUrl: "https://thenytrust.org/grantseekers/",
    programCode: "NYCT",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "FOUNDATION",
  },
  {
    title: "Google Ad Grants for Nonprofits",
    slug: "google-ad-grants-nonprofits",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "Google for Nonprofits",
    agencyAcronym: "Google",
    shortSummary:
      "In-kind grant of up to $10,000 per month in Google Search advertising for eligible nonprofits — effectively " +
      "$120,000 per year in donated ad spend to drive donations, volunteer recruitment, and program awareness. " +
      "Part of the free Google for Nonprofits program.",
    keyRequirements: [
      "Must hold valid charity status (501(c)(3) in the U.S.) and verify via Goodstack",
      "Hospitals, schools, and government organizations are not eligible (educational arms may be)",
      "Website must be functional, secure (HTTPS), and owned by the nonprofit",
      "Account must maintain program policies — e.g., meaningful keywords and a 5% minimum click-through rate",
    ],
    industryCategories: ["Technology", "Government & Nonprofit"],
    incentiveType: "SUBSIDY",
    fundingAmount: 120000,
    deadline: null,
    sourceUrl: "https://www.google.com/grants/",
    programCode: "GOOG-ADG",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "CORPORATE",
  },
  {
    title: "Walmart — Spark Good Local Community Grants",
    slug: "walmart-spark-good-local-grants",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "Walmart / Walmart Foundation",
    agencyAcronym: "Walmart",
    shortSummary:
      "Small cash grants of $250 to $5,000 awarded by local Walmart and Sam's Club facilities to nonprofits serving " +
      "their immediate communities — hunger relief, education, health, and community betterment. Applications are " +
      "accepted on a rolling basis through the Spark Good portal (quarterly cycles).",
    keyRequirements: [
      "Applicant must be a 501(c)(3) public charity (or equivalent eligible entity) verified via Deed",
      "Program must benefit the service area of the specific Walmart/Sam's Club facility applied to",
      "Requests range $250-$5,000; organizations may receive up to 25 local grants per year",
      "Apply through Walmart's Spark Good local grants portal",
    ],
    industryCategories: ["Human Services", "Community Development", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 5000,
    deadline: null,
    sourceUrl: "https://walmart.org/how-we-give/local-community-grants",
    programCode: "WMT-LCG",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "CORPORATE",
  },
  {
    title: "Bank of America Charitable Foundation — Economic Mobility Grants",
    slug: "bank-of-america-economic-mobility-grants",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "Bank of America Charitable Foundation",
    agencyAcronym: "BofA",
    shortSummary:
      "Twice-yearly competitive RFPs funding nonprofits that advance economic mobility — one cycle focused on basic needs " +
      "and workforce development for individuals and families, the other on affordable housing, small business support, " +
      "and neighborhood revitalization for communities.",
    keyRequirements: [
      "501(c)(3) organizations serving communities where Bank of America operates",
      "Two annual RFP windows (typically January-February and May-June) — check current focus areas",
      "Programs should produce measurable economic mobility outcomes",
      "Apply online through the foundation's grant portal during an open cycle",
    ],
    industryCategories: ["Human Services", "Community Development", "Housing & Homelessness", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 50000,
    deadline: null,
    sourceUrl: "https://about.bankofamerica.com/en/making-an-impact/charitable-foundation-funding",
    programCode: "BOFA-EM",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "CORPORATE",
  },
  {
    title: "Patagonia Environmental Grants",
    slug: "patagonia-environmental-grants",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "Patagonia Works",
    agencyAcronym: "Patagonia",
    shortSummary:
      "Funds small grassroots environmental organizations taking direct action to protect land, water, climate, and " +
      "biodiversity — prioritizing community-led activism and campaigns with clear goals over large institutional " +
      "conservation groups. Typical grants run $10,000-$20,000 through retail store and corporate giving channels.",
    keyRequirements: [
      "Applicant should be a grassroots environmental organization (501(c)(3) or fiscally sponsored)",
      "Work must be action-oriented: campaigns, organizing, and advocacy rather than research or education alone",
      "Applications reviewed through Patagonia's corporate and retail grants councils",
      "Multinational or large-budget organizations are generally not funded",
    ],
    industryCategories: ["Environment & Conservation", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 20000,
    deadline: null,
    sourceUrl: "https://www.patagonia.com/how-we-fund/",
    programCode: "PAT-ENV",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT"],
    funderType: "CORPORATE",
  },
  {
    title: "The Home Depot Foundation — Community Impact Grants",
    slug: "home-depot-community-impact-grants",
    jurisdictionLevel: "FOUNDATION",
    jurisdictionName: "United States",
    managingAgency: "The Home Depot Foundation",
    agencyAcronym: "THD",
    shortSummary:
      "Awards up to $5,000 in Home Depot gift cards to nonprofits and public agencies using volunteers to improve " +
      "communities — repairing homes for veterans, weatherization for seniors, playground builds, and disaster " +
      "recovery projects. Rolling applications with priority for veteran-serving projects.",
    keyRequirements: [
      "Applicant must be a registered 501(c)(3), public school, or tax-exempt public service agency",
      "Project must be volunteer-driven community improvement completed within six months",
      "Awards are Home Depot gift cards (up to $5,000) for tools and materials",
      "Veteran-focused and disaster-relief projects receive priority",
    ],
    industryCategories: ["Community Development", "Housing & Homelessness", "Construction", "Government & Nonprofit"],
    incentiveType: "GRANT",
    fundingAmount: 5000,
    deadline: null,
    sourceUrl: "https://corporate.homedepot.com/foundation",
    programCode: "THD-CIG",
    status: "ACTIVE",
    isVerified: true,
    scraperSource: "manual_research",
    eligibleEntityTypes: ["NONPROFIT", "GOVERNMENT"],
    funderType: "CORPORATE",
  },
];
