// Other states with hidden incentive programs
export const otherPrograms = [
  {
    title: "New York Consolidated Funding Application (CFA)",
    slug: "new-york-cfa-economic-development",
    jurisdictionLevel: "STATE", jurisdictionName: "New York",
    managingAgency: "Empire State Development / Multiple Agencies", agencyAcronym: "ESD",
    shortSummary: "Single application gateway to 20+ New York state funding programs — ESD business grants, NYSERDA clean energy incentives, DEC environmental grants, and more. One application, over $750M in annual state funding. Applications open annually July–September.",
    keyRequirements: ["Business or organization located in New York","Identify applicable programs within the single CFA form","Annual application period typically July–September","Projects must align with Regional Economic Development Council priorities","Award decisions announced in December by regional councils"],
    industryCategories: ["Manufacturing","Clean Technology","Agriculture","Technology","Government & Nonprofit"],
    incentiveType: "GRANT", fundingAmount: 5000000, deadline: null,
    sourceUrl: "https://regionalcouncils.ny.gov/cfa", programCode: "NY-CFA", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "New Jersey NJEDA Net Zero Building Fund",
    slug: "nj-njeda-net-zero-building-fund",
    jurisdictionLevel: "STATE", jurisdictionName: "New Jersey",
    managingAgency: "New Jersey Economic Development Authority", agencyAcronym: "NJEDA",
    shortSummary: "Low-interest loans ($100K–$5M) and grants (up to $500K for nonprofits/affordable housing) for NJ commercial building owners implementing net-zero energy upgrades including solar, battery storage, heat pump HVAC, and EV charging.",
    keyRequirements: ["Commercial or industrial building owner in New Jersey","Project must achieve net-zero or significant emission reduction","Eligible: solar PV, battery storage, heat pump HVAC, LED, insulation, EV charging","Buildings in Opportunity Zones receive enhanced incentives","Projects must be completed by licensed NJ contractors"],
    industryCategories: ["Building Electrification","Real Estate","Energy Storage","Clean Technology"],
    incentiveType: "LOAN", fundingAmount: 5000000, deadline: null,
    sourceUrl: "https://www.njeda.com/clean-energy/", programCode: "NJ-NZB", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Massachusetts MassCEC Advanced Efficiency Services",
    slug: "ma-cec-advanced-efficiency",
    jurisdictionLevel: "STATE", jurisdictionName: "Massachusetts",
    managingAgency: "Massachusetts Clean Energy Center", agencyAcronym: "MassCEC",
    shortSummary: "Free energy audits, $20K feasibility study grants, and 20–50% implementation grants for Massachusetts manufacturers with $100K+ annual energy spend. Covers compressed air, process heat, motor upgrades, and electrification.",
    keyRequirements: ["Massachusetts-based manufacturing or industrial business","Facility must have annual energy spend of at least $100,000","Program covers: free audits, $20K feasibility grants, implementation grants (20–50% of project cost)","Eligible: compressed air, motor upgrades, process heat recovery, electrification","Must implement recommendations within 24 months of audit"],
    industryCategories: ["Manufacturing","Energy Management","Building Electrification","Clean Technology"],
    incentiveType: "GRANT", fundingAmount: 500000, deadline: null,
    sourceUrl: "https://www.masscec.com/program/advanced-efficiency-services", programCode: "MA-AES", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Oregon Business Energy Tax Credit (BETC) — Pass-Through Option",
    slug: "oregon-betc-pass-through",
    jurisdictionLevel: "STATE", jurisdictionName: "Oregon",
    managingAgency: "Oregon Department of Energy", agencyAcronym: "ODOE",
    shortSummary: "35–50% Oregon tax credit for renewable energy and efficiency projects. Businesses unable to use the full credit can sell it to an investor for immediate cash (~85–90 cents/dollar) — making it accessible to nonprofits and startups with limited tax liability.",
    keyRequirements: ["Oregon business with qualifying clean energy or efficiency investment","Eligible: solar, wind, geothermal, biomass, EV charging, anaerobic digestion, CHP","Tax credit: 35% of eligible costs (50% for Rural Enterprise Zone projects)","Pass-through: sell credit to third-party investor for ~85–90 cents on the dollar","Apply through Oregon Department of Energy before project completion"],
    industryCategories: ["Clean Technology","Energy Storage","Agriculture","Manufacturing"],
    incentiveType: "TAX_CREDIT", fundingAmount: 10000000, deadline: null,
    sourceUrl: "https://www.oregon.gov/energy/Incentives/Pages/RETC.aspx", programCode: "OR-BETC", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Hawaii GEMS Green Energy Market Securitization Loan",
    slug: "hawaii-gems-loan",
    jurisdictionLevel: "STATE", jurisdictionName: "Hawaii",
    managingAgency: "Hawaii Green Infrastructure Authority", agencyAcronym: "HGIA",
    shortSummary: "Low-interest loans (as low as 2.5%) for Hawaii solar, battery storage, and energy efficiency projects serving low-to-moderate income customers and small businesses. Funded by utility customer charge securitization — a sustainable revolving loan fund.",
    keyRequirements: ["Project must be located in Hawaii","Eligible: rooftop solar, battery storage, EV charging, HVAC, LED, weatherization","Loan amounts: $5,000–$100,000 at 2.5–5% fixed interest; 5–15 year terms","Low-income households receive lowest rates and may qualify for companion grants","No prepayment penalty"],
    industryCategories: ["Clean Technology","Energy Storage","Building Electrification","EV Charging"],
    incentiveType: "LOAN", fundingAmount: 100000, deadline: null,
    sourceUrl: "https://hgia.hawaii.gov/gems/", programCode: "HI-GEMS", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Nevada GOED Clean Energy Diversification Incentives",
    slug: "nevada-goed-clean-energy-diversification",
    jurisdictionLevel: "STATE", jurisdictionName: "Nevada",
    managingAgency: "Nevada Governor's Office of Economic Development", agencyAcronym: "GOED",
    shortSummary: "Sales tax abatements (up to 2%), property tax abatements, and Modified Business Tax credits for clean energy manufacturers locating or expanding in Nevada. Targets solar, wind, battery storage, and EV-related product manufacturers creating 10+ jobs.",
    keyRequirements: ["Business must be in qualifying clean energy industry: solar, wind, storage, EV, grid tech","New or expanding Nevada operation creating minimum 10 full-time jobs","Jobs must pay 110%+ of county average wage with health benefits","Minimum capital investment: $1M rural, $3.5M urban Nevada","Application through GOED board prior to project commencement"],
    industryCategories: ["Clean Technology","Manufacturing","Energy Storage","EV Charging"],
    incentiveType: "TAX_CREDIT", fundingAmount: null, deadline: null,
    sourceUrl: "https://goed.nv.gov/incentives/", programCode: "NV-GOED-CE", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "New Mexico Commercial Solar & Storage Tax Credit",
    slug: "new-mexico-clean-energy-tax-credit",
    jurisdictionLevel: "STATE", jurisdictionName: "New Mexico",
    managingAgency: "New Mexico Taxation and Revenue Department", agencyAcronym: "NM TRD",
    shortSummary: "10% income tax credit for commercial solar PV and thermal installations, plus a separate 5% credit for battery storage. Combined with the federal ITC, New Mexico businesses can offset 40–50% of clean energy project costs.",
    keyRequirements: ["Business must be a New Mexico taxpayer with qualifying solar or storage installation","Solar PV: 10% of eligible costs (no cap for commercial since 2020)","Battery storage: 5% of eligible costs as separate credit","System must be installed and operational in the tax year claimed","Credits are non-refundable but carry forward 5 years"],
    industryCategories: ["Clean Technology","Energy Storage","Building Electrification","Agriculture"],
    incentiveType: "TAX_CREDIT", fundingAmount: null, deadline: null,
    sourceUrl: "https://www.tax.newmexico.gov/businesses/credits/", programCode: "NM-CE-TC", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Utah REDI — Rural Economic Development Initiative",
    slug: "utah-redi",
    jurisdictionLevel: "STATE", jurisdictionName: "Utah",
    managingAgency: "Utah Governor's Office of Economic Opportunity", agencyAcronym: "Utah OEO",
    shortSummary: "30% state income tax credit on new employee wages for businesses creating 5+ jobs in rural Utah Economic Opportunity Zones. Meaningful incentive to locate outside Salt Lake's urban corridor, with a 5-year credit period.",
    keyRequirements: ["Business must locate or expand in a Rural Economic Opportunity Zone","Minimum 5 new full-time jobs paying above-average rural county wages","Credit: 30% of wages paid to qualifying new employees for 5 years","Jobs must include health benefits and be held at least 12 months","Pre-approval through Utah OEO before hiring commences"],
    industryCategories: ["Manufacturing","Technology","Agriculture","Clean Technology"],
    incentiveType: "TAX_CREDIT", fundingAmount: null, deadline: null,
    sourceUrl: "https://business.utah.gov/programs/rural/", programCode: "UT-REDI", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Pennsylvania Ben Franklin Technology Partners — Innovation Grant",
    slug: "pennsylvania-ben-franklin-sbig",
    jurisdictionLevel: "STATE", jurisdictionName: "Pennsylvania",
    managingAgency: "Ben Franklin Technology Partners (4 regional centers)", agencyAcronym: "BFTP",
    shortSummary: "Grants of $25,000–$100,000 plus hands-on mentorship for Pennsylvania technology startups and early-stage manufacturers in advanced manufacturing, life sciences, IT, and clean energy. Four regional centers across PA.",
    keyRequirements: ["Technology-focused startup or early-growth company in Pennsylvania","Must demonstrate innovative product, process, or service with commercial potential","Eligible: advanced manufacturing, life sciences, IT, clean tech, agtech","Investment/grant: $25K–$100K; mentorship and network access included","Competitive application to one of four regional BFTP centers"],
    industryCategories: ["Technology","Manufacturing","Clean Technology","Healthcare","Research & Development"],
    incentiveType: "GRANT", fundingAmount: 100000, deadline: null,
    sourceUrl: "https://www.benfranklin.org/", programCode: "PA-BFTP", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Maryland MEA Clean Energy Grant — Commercial Buildings",
    slug: "maryland-mea-clean-energy-grant",
    jurisdictionLevel: "STATE", jurisdictionName: "Maryland",
    managingAgency: "Maryland Energy Administration", agencyAcronym: "MEA",
    shortSummary: "Grants up to $75,000 (25% of eligible costs) for Maryland businesses, nonprofits, and local governments installing solar, CHP, geothermal, anaerobic digestion, or battery storage. Enhanced grants for Opportunity Zone and brownfield projects.",
    keyRequirements: ["Business, nonprofit, or local government in Maryland","Eligible: solar PV, small wind, geothermal, CHP, anaerobic digestion, battery storage","Grant: up to 25% of eligible project costs, max $75,000","Priority for Opportunity Zones, brownfields, or LMI communities","Annual competitive solicitation through MEA"],
    industryCategories: ["Clean Technology","Energy Storage","Building Electrification","Manufacturing"],
    incentiveType: "GRANT", fundingAmount: 75000, deadline: null,
    sourceUrl: "https://energy.maryland.gov/business/Pages/incentives/cleangrant.aspx", programCode: "MD-MEA-CE", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Connecticut Green Bank C-PACE Commercial Property Financing",
    slug: "connecticut-green-bank-cpace",
    jurisdictionLevel: "STATE", jurisdictionName: "Connecticut",
    managingAgency: "Connecticut Green Bank", agencyAcronym: "CT Green Bank",
    shortSummary: "100% financing for energy efficiency, renewable energy, and resiliency upgrades on commercial CT properties — no upfront cost. Repayment is via property tax assessment, transfers with property sale, and is typically cash-flow positive from day one.",
    keyRequirements: ["Commercial, industrial, multifamily (5+ units), or nonprofit property in Connecticut","Eligible: solar, battery storage, HVAC, insulation, LED, EV charging, resiliency","100% project financing — no down payment required","Repayment via property tax bill over 10–25 years; transfers with sale","Property must have current local tax payments (not in arrears)"],
    industryCategories: ["Building Electrification","Real Estate","Energy Storage","Clean Technology"],
    incentiveType: "LOAN", fundingAmount: 5000000, deadline: null,
    sourceUrl: "https://ctgreenbank.com/c-pace/", programCode: "CT-CPACE", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Maricopa County ADEQ Clean Air Construction Equipment Program",
    slug: "maricopa-adeq-clean-air-construction",
    jurisdictionLevel: "AGENCY", jurisdictionName: "Phoenix, AZ",
    managingAgency: "Maricopa County Air Quality Department", agencyAcronym: "MCAQD",
    shortSummary: "VW Mitigation Trust and EPA DERA grants for contractors replacing Tier 0–2 diesel construction equipment in Maricopa County (Phoenix metro). Covers up to 60% for Tier 4 Final and up to 80% for zero-emission replacements.",
    keyRequirements: ["Construction or off-road equipment operated in Maricopa County, AZ","Existing equipment must be Tier 0–2 diesel engine","Replacement must be Tier 4 Final diesel or zero/near-zero emission","Old equipment must be permanently retired and destroyed","Business must have owned equipment for at least 2 years"],
    industryCategories: ["Construction","Fleet","Agriculture"],
    incentiveType: "GRANT", fundingAmount: 250000, deadline: null,
    sourceUrl: "https://www.maricopa.gov/5504/Air-Quality", programCode: "MCAQD-CACP", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Puget Sound Clean Air Agency Diesel Reduction Grants",
    slug: "pscaa-diesel-reduction-grants",
    jurisdictionLevel: "AGENCY", jurisdictionName: "Seattle, WA",
    managingAgency: "Puget Sound Clean Air Agency", agencyAcronym: "PSCAA",
    shortSummary: "VW Environmental Mitigation Trust grants for replacing older diesel trucks, buses, and off-road equipment in King, Pierce, Snohomish, and Kitsap counties. Covers 25–75% of replacement cost; ZEV replacements receive maximum funding.",
    keyRequirements: ["Equipment must operate primarily in King, Pierce, Snohomish, or Kitsap counties","Old equipment must be diesel and meet minimum age/emission tier requirements","Replacement must be Tier 4 Final or zero-emission","Business, nonprofit, or government agency must submit scrappage documentation","Annual solicitation through PSCAA grant portal"],
    industryCategories: ["Construction","Fleet","Logistics","Public Transit"],
    incentiveType: "GRANT", fundingAmount: 300000, deadline: null,
    sourceUrl: "https://www.pscleanair.gov/275/Grants", programCode: "PSCAA-DR", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "North Carolina Clean Energy Technology Center Business Grant",
    slug: "nc-cetc-business-grant",
    jurisdictionLevel: "STATE", jurisdictionName: "North Carolina",
    managingAgency: "NC Clean Energy Technology Center / NC State University", agencyAcronym: "NCCETC",
    shortSummary: "Free energy audits, feasibility studies, and implementation grants up to $25,000 for NC businesses, municipalities, and nonprofits. Focuses on efficiency, solar, and clean energy with priority for rural areas and coal transition counties.",
    keyRequirements: ["North Carolina business, local government, nonprofit, or educational institution","Free energy audits and solar feasibility studies available","Implementation grants up to $25,000 for projects with verified energy savings","Priority for small businesses, rural operations, and coal transition counties","Rolling applications; NCCETC staff provide technical support"],
    industryCategories: ["Energy Management","Clean Technology","Building Electrification","Manufacturing"],
    incentiveType: "GRANT", fundingAmount: 25000, deadline: null,
    sourceUrl: "https://nccleantech.ncsu.edu/", programCode: "NCCETC-BG", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "TVA EnergyRight Solutions — Commercial & Industrial Rebates",
    slug: "tva-energyright-commercial",
    jurisdictionLevel: "AGENCY", jurisdictionName: "Tennessee",
    managingAgency: "Tennessee Valley Authority", agencyAcronym: "TVA",
    shortSummary: "Rebates up to $50,000 for commercial businesses in TVA's 7-state service territory (TN, AL, MS, KY, GA, NC, VA) for LED lighting, HVAC upgrades, building controls, and refrigeration. Custom rebates available for industrial process efficiency projects.",
    keyRequirements: ["Commercial or industrial TVA power customer in one of 7 TVA states","Eligible: LED ($0.10/kWh saved), HVAC (up to $300/ton), building automation, refrigeration","Rebates paid within 90 days of installation verification","No minimum project size; large projects may qualify for enhanced custom rebates","EnergyRight manages audit and rebate processing"],
    industryCategories: ["Energy Management","Building Electrification","Manufacturing","Retail"],
    incentiveType: "POINT_OF_SALE_REBATE", fundingAmount: 50000, deadline: null,
    sourceUrl: "https://www.tva.com/energy/solution-finder/energyright-solutions", programCode: "TVA-ER", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
  {
    title: "Michigan EGLE Clean Air Nonattainment Area Business Grant",
    slug: "michigan-egle-clean-air-business-grant",
    jurisdictionLevel: "STATE", jurisdictionName: "Michigan",
    managingAgency: "Michigan Department of Environment, Great Lakes and Energy", agencyAcronym: "EGLE",
    shortSummary: "Grants covering up to 50% of emission reduction project costs for Michigan businesses in air quality nonattainment areas (priority: Southeast Michigan). Targets NOx, PM2.5, and VOC reductions from boilers, industrial processes, and diesel fleets.",
    keyRequirements: ["Business in a Michigan air quality nonattainment or maintenance area","Project must reduce NOx, PM2.5, VOC, or other NAAQS criteria pollutants","Eligible: boiler upgrades, industrial process modifications, diesel fleet upgrades","Grants cover up to 50% of eligible emission reduction project costs","Applications reviewed quarterly by EGLE Air Quality Division"],
    industryCategories: ["Manufacturing","Fleet","Construction","Energy Management"],
    incentiveType: "GRANT", fundingAmount: 250000, deadline: null,
    sourceUrl: "https://www.michigan.gov/egle/about/organization/air-quality", programCode: "MI-EGLE-CANA", status: "ACTIVE", isVerified: true, scraperSource: "state_scraper",
  },
];
